name: Update GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # config.jsにGitHubトークンを注入
      - name: Update config.js with GitHub token
        run: |
          sed -i "s/TOKEN: ''/TOKEN: '${{ secrets.API_TOKEN }}'/" config.js
