name: Update GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      # リポジトリのチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # config.jsにGitHubトークンを注入
      - name: Update config.js with GitHub token and repo info
        env:
          REPO_OWNER: ${{ github.repository_owner }}
        run: |
          sed -i "s/OWNER: '.*'/OWNER: '$REPO_OWNER'/" config.js
          sed -i 's/TOKEN: ""/TOKEN: "${{ secrets.API_TOKEN }}"/' config.js
          cat config.js # デバッグ用に内容を表示

      - name: Create data.json if not exists
        run: |
          if [ ! -f data.json ]; then
            echo '[]' > data.json
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add data.json
            git commit -m "Create initial data.json"
            git push
          fi
